//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal TitleFontSetting {
            get {
                return ((decimal)(this["TitleFontSetting"]));
            }
            set {
                this["TitleFontSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TitleBoldSetting {
            get {
                return ((bool)(this["TitleBoldSetting"]));
            }
            set {
                this["TitleBoldSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitleItalicSetting {
            get {
                return ((bool)(this["TitleItalicSetting"]));
            }
            set {
                this["TitleItalicSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitleUnderlineSetting {
            get {
                return ((bool)(this["TitleUnderlineSetting"]));
            }
            set {
                this["TitleUnderlineSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public decimal TableFontSetting {
            get {
                return ((decimal)(this["TableFontSetting"]));
            }
            set {
                this["TableFontSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TableBoldSetting {
            get {
                return ((bool)(this["TableBoldSetting"]));
            }
            set {
                this["TableBoldSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TableItalicSetting {
            get {
                return ((bool)(this["TableItalicSetting"]));
            }
            set {
                this["TableItalicSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TableUnderlineSetting {
            get {
                return ((bool)(this["TableUnderlineSetting"]));
            }
            set {
                this["TableUnderlineSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATTENDED")]
        public string FirstNameSetting {
            get {
                return ((string)(this["FirstNameSetting"]));
            }
            set {
                this["FirstNameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FIRST NAME")]
        public string SecondNameSetting {
            get {
                return ((string)(this["SecondNameSetting"]));
            }
            set {
                this["SecondNameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAST NAME")]
        public string ThirdNameSetting {
            get {
                return ((string)(this["ThirdNameSetting"]));
            }
            set {
                this["ThirdNameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STATUS")]
        public string FourthNameSetting {
            get {
                return ((string)(this["FourthNameSetting"]));
            }
            set {
                this["FourthNameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public decimal FirstNumSetting {
            get {
                return ((decimal)(this["FirstNumSetting"]));
            }
            set {
                this["FirstNumSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal SecondNumSetting {
            get {
                return ((decimal)(this["SecondNumSetting"]));
            }
            set {
                this["SecondNumSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal ThirdNumSetting {
            get {
                return ((decimal)(this["ThirdNumSetting"]));
            }
            set {
                this["ThirdNumSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal FourthNumSetting {
            get {
                return ((decimal)(this["FourthNumSetting"]));
            }
            set {
                this["FourthNumSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal NumEmptySetting {
            get {
                return ((decimal)(this["NumEmptySetting"]));
            }
            set {
                this["NumEmptySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal SubtitleFontSetting {
            get {
                return ((decimal)(this["SubtitleFontSetting"]));
            }
            set {
                this["SubtitleFontSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SubtitleBoldSetting {
            get {
                return ((bool)(this["SubtitleBoldSetting"]));
            }
            set {
                this["SubtitleBoldSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitleItalicSetting {
            get {
                return ((bool)(this["SubtitleItalicSetting"]));
            }
            set {
                this["SubtitleItalicSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitleUnderlineSetting {
            get {
                return ((bool)(this["SubtitleUnderlineSetting"]));
            }
            set {
                this["SubtitleUnderlineSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 14pt")]
        public global::System.Drawing.Font TitleFontTypeSetting {
            get {
                return ((global::System.Drawing.Font)(this["TitleFontTypeSetting"]));
            }
            set {
                this["TitleFontTypeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 10pt")]
        public global::System.Drawing.Font SubtitleFontTypeSetting {
            get {
                return ((global::System.Drawing.Font)(this["SubtitleFontTypeSetting"]));
            }
            set {
                this["SubtitleFontTypeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 11pt")]
        public global::System.Drawing.Font TableFontTypeSetting {
            get {
                return ((global::System.Drawing.Font)(this["TableFontTypeSetting"]));
            }
            set {
                this["TableFontTypeSetting"] = value;
            }
        }
    }
}
